apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    - name: lib
      mountPath: /var/lib/kubelet
    ports:
    - containerPort: 80
  volumes:
  - name: lib
    hostPath:
      path: /var/lib/kubelet
  - name: test
    flexVolume:
      driver: "px/flexvolume"
      fsType: "ext4"
      options:
        volumeID: "426908272665195885"
        size: "1G"
        osdDriver: "pxd"

