kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pwx-claim-repl2
  annotations:
    volume.beta.kubernetes.io/storage-class: "repl2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
