apiVersion: v1
kind: Pod
metadata:
  name: nginx-px-wo-pvc
spec:
  hostIPC: true
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
    volumeMounts:
    - name: test-volume
      mountPath: /data
    - name: lib
      mountPath: /var/lib/kubelet
    - name: run
      mountPath: /run
    - name: sys
      mountPath: /sys
    ports:
    - containerPort: 80
  volumes:
    - name: test-volume
      pwxVolume:
        volumeID: "1126916133888942870"
        volumeLabels: ""
    - name: lib
      hostPath:
        path: /var/lib/kubelet
    - name: run
      hostPath:
        path: /run
    - name: sys
      hostPath:
        path: /sys
