apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  pwxVolume:
    volumeID: "vol1"
    fsType: "xfs"
    ha_level: 1
    shared: true
